# Generated by Django 6.0 on 2026-01-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_profiles/'),
        ),
    ]
