# Generated by Django 5.2.8 on 2026-03-06 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pharmacie_localisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.client')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.pharmacie')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineNotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to='api.client')),
            ],
            options={
                'unique_together': {('client', 'medicine_name')},
            },
        ),
    ]
