# Generated by Django 5.2.8 on 2026-03-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicinenotification_medicinenotificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.pharmacie'),
        ),
    ]
