# Generated by Django 5.2.8 on 2026-03-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commande_pharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='pharmacie',
        ),
    ]
